FORMAT: 1A
HOST: http://api.betterthanmostsports.com/

# Baseball-API

This API uses an open source database from Sean Lehman to render all historical baseball stats. Included are various advanced SABRmetrics.

# Group Player

## Players Index [/players]

### List Players [GET]

+ Response 200 (application/json)


        {
            id: "541fd425-c4ab-4618-9521-4b3e1362b610",
            type: "players",
            attributes: {
                "name_first": "David",
                "name_last": "Aardsma",
                "name_given": "David Allan",
                "birth_day": 27,
                "birth_month": 12,
                "birth_year": 1981,
                "birth_state": "CO",
                "birth_city": "Denver",
                "weight": 205,
                "height": 75,
                "bats": "R",
                "throws": "R",
                "debut": "2004-04-06T05:00:00.000Z"
                }
                
        }


## Player [/players/{id}]

+ Parameters
    + id (string) ... UUID of player

### Player [GET]

+ Response 200 (application/json)

        {
            "data": 
            [
    
                {
                  "id": "541fd425-c4ab-4618-9521-4b3e1362b610",
                  "type": "players",
                  "attributes": {
                    "name_first": "David",
                    "name_last": "Aardsma",
                    "name_given": "David Allan",
                    "birth_day": 27,
                    "birth_month": 12,
                    "birth_year": 1981,
                    "birth_state": "CO",
                    "birth_city": "Denver",
                    "weight": 205,
                    "height": 75.0,
                    "bats": "R",
                    "throws": "R",
                    "debut": "2004-04-06T05:00:00.000Z"
                    }
                }
            ]
        }

## Player Reports [/players/{id}/report]

+ Parameters
    + id (string) ... UUID of player

### Career Report [GET]

This report will generate basic batting, fielding, and pitching stats for any players career. This report also includes a player comparison value. This can be used to compare like players.

+ Response 200 (application/json)

        {
            "data": 
            [
    
                {
                  "id": "721fb791-30b6-4767-a8f7-09df037fcdae",
                  "type": "reports",
                  "attributes": 
                  {
                    "batting": 
                    {
                      "games": 298,
                      "atbats": 3,
                      "batting_runs": 0,
                      "batting_hits": 0,
                      "batting_doubles": 0,
                      "batting_triples": 0,
                      "batting_homeruns": 0,
                      "batting_rbi": 0,
                      "batting_stolenbases": 0,
                      "batting_caughtstealing": 0,
                      "batting_walk": 0,
                      "batting_strikeout": 1,
                      "batting_intentionalwalks": 0,
                      "batting_hitbypitch": 0,
                      "batting_sacbunt": 1,
                      "batting_sacfly": 0,
                      "batting_gidp": 0,
                      "avg": 0.0,
                      "slg": 0.0,
                      "obp": 0.0,
                      "ops": 0.0,
                      "iso": 0.0,
                      "babip": 0.0,
                      "pa": 4.0,
                      "tb": 0.0
                    },
                    "pitching": 
                    {
                      "pitching_games": 298,
                      "pitching_wins": 15,
                      "pitching_losses": 17,
                      "pitching_gamesstarted": 0,
                      "pitching_completegames": 0,
                      "pitching_shutouts": 0,
                      "pitching_saves": 69,
                      "pitching_ipouts": 919,
                      "pitching_hits": 271,
                      "pitching_earnedruns": 144,
                      "pitching_homeruns": 35,
                      "pitching_walks": 169,
                      "pitching_strikeouts": 305,
                      "pitching_baopp": 2.093,
                      "pitching_era": 42.050000000000004,
                      "pitching_intentionalwalks": 19,
                      "pitching_wildpitches": 11,
                      "pitching_hitbypitch": 15,
                      "pitching_balk": 1,
                      "pitching_battersfaced": 1346,
                      "pitching_gamesfinished": 132,
                      "pitching_runs": 152,
                      "pitching_sacbunts": 17,
                      "pitching_sacflys": 10,
                      "pitching_gidp": 0
                    },
                    "fielding": 
                    {
                      "fielding_games": 298,
                      "fielding_gamesstarted": 0,
                      "fielding_innouts": 921,
                      "fielding_putouts": 11,
                      "fielding_assists": 28,
                      "fielding_errors": 2,
                      "fielding_doubleplay": 2,
                      "fielding_passedballs": 0,
                      "fielding_wildpitches": 0,
                      "fielding_stolenbases": 0,
                      "fielding_caughtstealing": 0,
                      "fielding_zonerating": 0
                    },
                    "battingpost": null,
                    "pitchingpost": null,
                    "fieldingpost": null,
                    "appearances": 
                    {
                      "G_all": 298,
                      "GS": 0,
                      "G_batting": 109,
                      "G_defense": 298,
                      "G_p": 298,
                      "G_c": 0,
                      "G_1b": 0,
                      "G_2b": 0,
                      "G_3b": 0,
                      "G_ss": 0,
                      "G_lf": 0,
                      "G_cf": 0,
                      "G_rf": 0,
                      "G_of": 0,
                      "G_dh": 0,
                      "G_ph": 0,
                      "G_pr": 0
                        }
                    }
                }
            ]
        }
        
## Player Comparison [/players/{id,id}]
This allows a user to compare multiple players in a single view. IDs need to be separated by a comma in the url.

+ Parameters
    + id (string) ... UUID of player

### Player [GET]

+ Response 200 (application/json)

        {
            "data": 
            [
    
                {
                  "id": "541fd425-c4ab-4618-9521-4b3e1362b610",
                  "type": "players",
                  "attributes": {
                    "name_first": "David",
                    "name_last": "Aardsma",
                    "name_given": "David Allan",
                    "birth_day": 27,
                    "birth_month": 12,
                    "birth_year": 1981,
                    "birth_state": "CO",
                    "birth_city": "Denver",
                    "weight": 205,
                    "height": 75.0,
                    "bats": "R",
                    "throws": "R",
                    "debut": "2004-04-06T05:00:00.000Z"
                    }
                },
                
                {
                  "id": "0ebc2767-af3e-43bc-907e-756bfc3e8b53",
                  "type": "players",
                  "attributes": 
                  {
                    "name_first": "Hank",
                    "name_last": "Aaron",
                    "name_given": "Henry Louis",
                    "birth_day": 5,
                    "birth_month": 2,
                    "birth_year": 1934,
                    "birth_state": "AL",
                    "birth_city": "Mobile",
                    "weight": 180,
                    "height": 72.0,
                    "bats": "R",
                    "throws": "R",
                    "debut": "1954-04-13T06:00:00.000Z"
                  }
            ]
        }

## Player Report Comparison [/players/{id,id}/report]

+ Parameters
    + id (string) ... UUID of player

### Career Report [GET]

This report is identical to the single player report simply including another player for side-by-side comparison.

+ Response 200 (application/json)

        {
            "data": 
            [
    
                {
                  "id": "721fb791-30b6-4767-a8f7-09df037fcdae",
                  "type": "reports",
                  "attributes": 
                  {
                    "batting": 
                    {
                      "games": 298,
                      "atbats": 3,
                      "batting_runs": 0,
                      "batting_hits": 0,
                      "batting_doubles": 0,
                      "batting_triples": 0,
                      "batting_homeruns": 0,
                      "batting_rbi": 0,
                      "batting_stolenbases": 0,
                      "batting_caughtstealing": 0,
                      "batting_walk": 0,
                      "batting_strikeout": 1,
                      "batting_intentionalwalks": 0,
                      "batting_hitbypitch": 0,
                      "batting_sacbunt": 1,
                      "batting_sacfly": 0,
                      "batting_gidp": 0,
                      "avg": 0.0,
                      "slg": 0.0,
                      "obp": 0.0,
                      "ops": 0.0,
                      "iso": 0.0,
                      "babip": 0.0,
                      "pa": 4.0,
                      "tb": 0.0
                    },
                    "pitching": 
                    {
                      "pitching_games": 298,
                      "pitching_wins": 15,
                      "pitching_losses": 17,
                      "pitching_gamesstarted": 0,
                      "pitching_completegames": 0,
                      "pitching_shutouts": 0,
                      "pitching_saves": 69,
                      "pitching_ipouts": 919,
                      "pitching_hits": 271,
                      "pitching_earnedruns": 144,
                      "pitching_homeruns": 35,
                      "pitching_walks": 169,
                      "pitching_strikeouts": 305,
                      "pitching_baopp": 2.093,
                      "pitching_era": 42.050000000000004,
                      "pitching_intentionalwalks": 19,
                      "pitching_wildpitches": 11,
                      "pitching_hitbypitch": 15,
                      "pitching_balk": 1,
                      "pitching_battersfaced": 1346,
                      "pitching_gamesfinished": 132,
                      "pitching_runs": 152,
                      "pitching_sacbunts": 17,
                      "pitching_sacflys": 10,
                      "pitching_gidp": 0
                    },
                    "fielding": 
                    {
                      "fielding_games": 298,
                      "fielding_gamesstarted": 0,
                      "fielding_innouts": 921,
                      "fielding_putouts": 11,
                      "fielding_assists": 28,
                      "fielding_errors": 2,
                      "fielding_doubleplay": 2,
                      "fielding_passedballs": 0,
                      "fielding_wildpitches": 0,
                      "fielding_stolenbases": 0,
                      "fielding_caughtstealing": 0,
                      "fielding_zonerating": 0
                    },
                    "battingpost": null,
                    "pitchingpost": null,
                    "fieldingpost": null,
                    "appearances": 
                    {
                      "G_all": 298,
                      "GS": 0,
                      "G_batting": 109,
                      "G_defense": 298,
                      "G_p": 298,
                      "G_c": 0,
                      "G_1b": 0,
                      "G_2b": 0,
                      "G_3b": 0,
                      "G_ss": 0,
                      "G_lf": 0,
                      "G_cf": 0,
                      "G_rf": 0,
                      "G_of": 0,
                      "G_dh": 0,
                      "G_ph": 0,
                      "G_pr": 0
                        }
                    },
                    
                    {
                      "id": "e20123fa-8a02-4767-9e47-0a04e1d39050",
                      "type": "reports",
                      "attributes": 
                      {
                        "batting": 
                        {
                          "games": 3298,
                          "atbats": 12364,
                          "batting_runs": 2174,
                          "batting_hits": 3771,
                          "batting_doubles": 624,
                          "batting_triples": 98,
                          "batting_homeruns": 755,
                          "batting_rbi": 2297,
                          "batting_stolenbases": 240,
                          "batting_caughtstealing": 73,
                          "batting_walk": 1402,
                          "batting_strikeout": 1383,
                          "batting_intentionalwalks": 293,
                          "batting_hitbypitch": 32,
                          "batting_sacbunt": 21,
                          "batting_sacfly": 121,
                          "batting_gidp": 328,
                          "avg": 0.30499838240051763,
                          "slg": 0.5545131025558072,
                          "obp": 0.3739492779653711,
                          "ops": 0.9284623805211782,
                          "iso": 0.24951472015528958,
                          "babip": 0.29554140127388534,
                          "pa": 13940.0,
                          "tb": 6856.0
                        },
                        "pitching": null,
                        "fielding": 
                        {
                          "fielding_games": 6019,
                          "fielding_gamesstarted": 5712,
                          "fielding_innouts": 150488,
                          "fielding_putouts": 12926,
                          "fielding_assists": 647,
                          "fielding_errors": 259,
                          "fielding_doubleplay": 258,
                          "fielding_passedballs": 0,
                          "fielding_wildpitches": 0,
                          "fielding_stolenbases": 0,
                          "fielding_caughtstealing": 0,
                          "fielding_zonerating": 0
                        },
                        "battingpost": 
                        {
                          "battingpost_runs": 11,
                          "battingpost_hits": 25,
                          "battingpost_doubles": 4,
                          "battingpost_triples": 1,
                          "battingpost_homeruns": 6,
                          "battingpost_rbi": 16,
                          "battingpost_stolenbases": 0,
                          "battingpost_caughtstealing": 0,
                          "battingpost_walks": 5,
                          "battingpost_strikeouts": 13,
                          "battingpost_intentionalwalks": 0,
                          "battingpost_hitbypitch": 0,
                          "battingpost_sacbunts": 0,
                          "battingpost_sacflys": 0,
                          "battingpost_gidp": 2,
                          "avgpost": 0.30499838240051763,
                          "slgpost": 0.5545131025558072,
                          "obppost": 0.3739492779653711,
                          "opspost": 0.9284623805211782,
                          "isopost": 0.24951472015528958,
                          "babippost": 0.29554140127388534,
                          "papost": 13940.0
                        },
                        "pitchingpost": null,
                        "fieldingpost": 
                        {
                          "fieldingpost_games": 18,
                          "fieldingpost_gamesstarted": 17,
                          "fieldingpost_innouts": 453,
                          "fieldingpost_putouts": 31,
                          "fieldingpost_assists": 1,
                          "fieldingpost_errors": 0,
                          "fieldingpost_doubleplay": 0,
                          "fieldingpost_passedballs": 0,
                          "fieldingpost_stolenbases": 0,
                          "fieldingpost_caughtstealing": 0
                        },
                        "appearances": 
                        {
                          "G_all": 3298,
                          "GS": 288,
                          "G_batting": 3298,
                          "G_defense": 3057,
                          "G_p": 0,
                          "G_c": 0,
                          "G_1b": 210,
                          "G_2b": 43,
                          "G_3b": 7,
                          "G_ss": 0,
                          "G_lf": 313,
                          "G_cf": 293,
                          "G_rf": 2184,
                          "G_of": 2760,
                          "G_dh": 196,
                          "G_ph": 46,
                          "G_pr": 0
                        }
                    }
                }
            ]
        }