FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Baseball-API

This API uses an open source database from Sean Lehman to render all historical baseball stats. Included are various advanced SABRmetrics.

## Players Index [/players]

### List All Players [GET]

+ Response 200 (application/json)

        [
            {
                id: "541fd425-c4ab-4618-9521-4b3e1362b610",
                type: "players",
                attributes: {
                    nameFirst: "David",
                    nameLast: "Aardsma",
                    nameGiven: "David Allan",
                    birthDay: 27,
                    birthMonth: 12,
                    birthYear: 1981,
                    birthState: "CO",
                    birthCity: "Denver",
                    weight: 205,
                    height: 75,
                    bats: "R",
                    throws: "R",
                    debut: "2004-04-06T05:00:00.000Z"
                    }
                ]
            }
        ]
        
## Player Reports [/players/player_id/report]

### Career Report [GET]

This report will generate basic batting, fielding, and pitching stats for any players career. This report also includes a player comparison value. This can be used to compare like players.

+ Response 200 (application/json)

        {
            id: "8195d33b-926d-46ca-ba9e-62eaa1854444",
            type: "reports",
            attributes: {
                BA: 0,
                H: 271,
                RBI: 0,
                HR: 35,
                batting_score: -939.2
            }
        }
