reporter: apiary
custom:
  apiaryApiKey: 1bfaf07b490fdd764519ed34a8135491
  apiaryApiName: stats12
dry-run: null
hookfiles: null
language: ruby
sandbox: false
server: PORT=5001 RACK_ENV=test bundle exec foreman s
server-wait: 5
init: false
names: false
only: []
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
blueprint: apiary.apib
endpoint: 'http://localhost:5001'
